Josh branch page
tameTNT/prog-b-group-site pull request #4
Opened 2021-10-27 09:41 UTC by KnightJam1

Add the medical contributions page

2021-10-31 13:08 UTC, tameTNT commented
I can't wait to try out whatever beautiful creation you've just added here...

2021-10-31 14:51 UTC, KnightJam1 commented
I dare you to press the "Do Not Press" button

2021-11-01 00:01 UTC, tameTNT requested changes
Mermermer he's requested changes *again*. This guy is never happy...

2021-11-01 15:16 UTC, KnightJam1 commented on medical.html
> +            audio.addEventListener("ended", function() {
No idea how you got that, I removed it a while ago??? Well, it's gone now.

2021-11-01 19:05 UTC, tameTNT commented on medical.html
> +            audio.addEventListener("ended", function() {
Probably like a forgot to fetch/push thing or smth idk? 🤷

2021-11-01 22:45 UTC, merged